### ISSUE TITLE
Too many open files path: /data/data/info.nightscout.android/files/default.realm.lock

### ISSUE THREAD

**Issue by volkerrichert** [pazaan/640gAndroidUploader#99]
tonight the uploader stops sending data to NS. 

#### Your Environment

* Uploader Version Number: 0.5.0-SNAPSHOT/b0e9f79
* Your Android Phone Model Name (e.g. Samsung J1 Ace): S4
* Android Version Number (e.g. use 4.4 for 4.4.4): 6.0.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): WiFi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.9.2

#### Uploader Error Code
NightscoutUploadIntentService at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:658)  
NightscoutUploadIntentService at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:632)  
NightscoutUploadIntentService at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:621)  
NightscoutUploadIntentService at info.nightscout.android.upload.nightscout.NightscoutUploadIntentService.uploadToNightscout(NightscoutUploadIntentService.java:236)  
NightscoutUploadIntentService at info.nightscout.android.upload.nightscout.NightscoutUploadIntentService.uploadToNightscout(NightscoutUploadIntentService.java:194)  
NightscoutUploadIntentService at info.nightscout.android.upload.nightscout.NightscoutUploadIntentService.doRESTUploadTo(NightscoutUploadIntentService.java:175)  
NightscoutUploadIntentService at info.nightscout.android.upload.nightscout.NightscoutUploadIntentService.doRESTUpload(NightscoutUploadIntentService.java:131)  
NightscoutUploadIntentService at info.nightscout.android.upload.nightscout.NightscoutUploadIntentService.onHandleIntent(NightscoutUploadIntentService.java:86)  
NightscoutUploadIntentService at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)  
NightscoutUploadIntentService at android.os.Handler.dispatchMessage(Handler.java:102)  
NightscoutUploadIntentService at android.os.Looper.loop(Looper.java:148)  
NightscoutUploadIntentService at android.os.HandlerThread.run(HandlerThread.java:61)  
NightscoutUploadIntentService Caused by: java.net.ConnectException: failed to connect to /78.94.75.102 (port 443) after 30000ms: connect failed: EMFILE (Too many open files)  
NightscoutUploadIntentService at libcore.io.IoBridge.connect(IoBridge.java:124)  
NightscoutUploadIntentService at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)  
NightscoutUploadIntentService at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)  
NightscoutUploadIntentService at java.net.Socket.connect(Socket.java:884)  
NightscoutUploadIntentService at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)  
NightscoutUploadIntentService at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)  
NightscoutUploadIntentService ... 16 more  
NightscoutUploadIntentService Caused by: android.system.ErrnoException: connect failed: EMFILE (Too many open files)  
NightscoutUploadIntentService at libcore.io.Posix.connect(Native Method)  
NightscoutUploadIntentService at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)  
NightscoutUploadIntentService at libcore.io.IoBridge.connectErrno(IoBridge.java:154)  
NightscoutUploadIntentService at libcore.io.IoBridge.connect(IoBridge.java:122)  
NightscoutUploadIntentService ... 21 more  
NightscoutUploadIntentService Unable to post data to: 'https://carelink.richert.nrw/api/v1//devicestatus'  
NightscoutUploadIntentService org.apache.http.conn.HttpHostConnectException: Connection to https://carelink.richert.nrw refused  
NightscoutUploadIntentService at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)  
NightscoutUploadIntentService at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)  
NightscoutUploadIntentService at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)  
NightscoutUploadIntentService at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)  
NightscoutUploadIntentService at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)

After that, there are many "Too many open files" related errors. a few hours later it stops working without any error message

Mon Jan 09 2017 02:09:17 GMT+0100 (Mitteleuropäische Zeit) NightscoutUploadIntentService Finished upload of 4 record using a REST API in 1352 ms
Mon Jan 09 2017 07:01:42 GMT+0100 (Mitteleuropäische Zeit) MainActivity onCreate called

there are no lines between.

**Comment by volkerrichert** [comment]
It seems to me, that the last request doesn't set the timer

**Comment by volkerrichert** [comment]
I'll take a closer look at the open files and try to monitor them

**Comment by volkerrichert** [comment]
fixed with 073f42ad49ea4cc2483d856d3373c1b4efc254a3

**Comment by volkerrichert** [comment]
@pazaan I sill can't push to master. this fix needed to be integrated into master. If i assume that 255 open handle are allowed (http://stackoverflow.com/questions/29117105/whats-the-max-number-of-file-descriptors-on-android) and we have 32 open at startup, 223 are left.

If one is blocked every 5 min we are running out of file handles after 44,6h wich is less than 2 days.

Volker
